name: Build and Publish Extension
on:
  push:
    branches:
      - release
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Publish
        run: |
          npm install
          npm i -g vsce
          vsce publish -p ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
